[package]
name = "engine-api"
version = "0.1.0"
edition = "2021"

[dependencies]
engine-branches = { path = "../engine-branches" }
engine-index = { path = "../engine-index" }
engine-journal = { path = "../engine-journal" }
engine-presentation = { path = "../engine-presentation" }
engine-sdk = { path = "../engine-sdk" }
engine-time = { path = "../engine-time" }
