[package]
name = "engine-presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
engine-sdk = { path = "../engine-sdk" }
engine-time = { path = "../engine-time" }

[dev-dependencies]
caravan-domain = { path = "../caravan-domain" }
caravan-reference = { path = "../caravan-reference" }
engine-journal = { path = "../engine-journal" }
